version: "3.1"
services:

  webserver:
    image: nginx:alpine
    container_name: aviv-elementor
    working_dir: /application
    volumes:
      - .:/application
      - ./front/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4001:80"
